version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    hostname : postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ToDoList
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=todolist@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 54321:80
    restart: always
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  app:
    build:
      context: .
      target: prod
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data: